### ISSUE TITLE
Gamma adjusted input colors

### ISSUE THREAD

**Issue by kvark** [kvark/three-rs#15]
All the colors specified for materials (and lights?) need to be converted to ~~sRGB~~ linear space before reaching the shaders.
cc @retep998 for possible clarification of the correct usage

**Comment by retep998** [comment]
It's really that the colors people specify are usually already in sRGB because that's what everything uses without realizing it. However some graphics engines and libraries correctly use *linear* color space internally, so sRGB constants need to be converted to linear before being used.

**Comment by kvark** [comment]
@retep998 thanks for the info! We certainly want to do all lighting in linear space, so we do need to convert the input colors. Another question is - are only material colors that need to be converted, or the light colors as well? It seems to me that the lights should be unaffected.

**Comment by retep998** [comment]
Any color constants (even light color constants) need to be converted to linear color space, unless the user explicitly provided them in linear color space already. Color textures are converted automatically by marking them as sRGB textures.

**Comment by kvark** [comment]
Fixed in 3f7127306dc14deecbcb6e8fad07b15e698a2915
