### ISSUE TITLE
Physically Based Rendering

### ISSUE THREAD

**Issue by kvark** [kvark/three-rs#21]

**Comment by alteous** [comment]
How do you vision this being implemented?

A simple way might alter the current `Material` type, by either replacing `Material` with one unified PBR version, or otherwise adding a `Pbr` variant to the list.

**Comment by kvark** [comment]
@alteous AFAIK, we just need to add a material type with the corresponding shader, similar to https://threejs.org/docs/#api/materials/MeshStandardMaterial

**Comment by alteous** [comment]
Is there anything left to implement for this feature?

**Comment by kvark** [comment]
Right, fixed in #61
