### ISSUE TITLE
Clean up math conversion code

### ISSUE THREAD

**Issue by kvark** [kvark/three-rs#65]
We had quite a few crappy manual conversions between `mint` and `cgmath` types. This is all obsolete now, fortunately, given that cgmath-0.15 has been published with native `mint` support.

**Comment by shmutalov** [comment]
Oh, Zeus! Good news! Time to remove 
```rust
self.camera_q = key_q * self.camera_q;
self.camera_q = self.camera_q.normalize();

let rv: [f32; 3] = self.camera_q.v.into();
let rot = mint::Quaternion {
   s: self.camera_q.s,
   v: rv.into(),
};
```

crap!
