### ISSUE TITLE
Re-export gfx::Primitive

### ISSUE THREAD

**Issue by alteous** [kvark/three-rs#76]
The custom material / pso API is great but it seems the user has to import `gfx` in order to provide `gfx::Primitive` in `Factory::basic_pipeline()`. Could this be re-exported for convenience?

**Comment by vitvakatu** [comment]
I have the same concern.

**Comment by kvark** [comment]
It's in there:
https://github.com/kvark/three-rs/blob/8537e513ffabc95d2914820c7f116671aef453ad/src/lib.rs#L50
