### ISSUE TITLE
Camera orientation issue

### ISSUE THREAD

**Issue by alteous** [kvark/three-rs#77]
I'm running into a problem when using `Camera::set_transform()`, whereby the world is unintentionally flipped upside down. It may be my own error, but I'm not 100% sure.

See https://github.com/alteous/three-rs/tree/oops for a reproducible example (`cargo run --example oops`). You will have to either clone my repo or re-export `camera::Projection` for the project to build. 

When run, the triangle should turn yellow when the mouse pointer is inside its area, and appear red otherwise. [`zrot` is used to flip the world the right way up](https://github.com/alteous/three-rs/blob/oops/examples/oops.rs#L85-L93), but using the same view matrix to [unproject the camera ray](https://github.com/alteous/three-rs/blob/oops/examples/oops.rs#L105-L112) leads to incorrect results. This suggests that the scene co-ordinates are inconsistent with the intended world co-ordinates.

**Comment by alteous** [comment]
[Here's the culprit](https://docs.rs/cgmath/0.14.0/src/cgmath/quaternion.rs.html#697). As @kvark suggested, it was the `[f32; 4] -> mint::Quaternion` conversion that was incorrect.

**Comment by vitvakatu** [comment]
Just wanted to say about it. Glad to see this issue fixed. By the way, you can use `cgmath` -> `mint` conversions directly.

**Comment by alteous** [comment]
Not without https://github.com/kvark/three-rs/pull/78/files, if I'm not mistaken.
