### ISSUE TITLE
Input format

### ISSUE THREAD

**Issue by kvark** [kvark/three-rs#8]
Three.js doesn't appear to provide a single structure for all the input per frame.
Main problem is - some use cases need an impulse mode (has "X" just been hit?), some need a modal one (is "x" currently pressed?). We night end up doing both.

**Comment by vitvakatu** [comment]
I suppose the simplest variant will be just an array/hashmap for all keys with current state (boolean pressed\released, nothing more), plus events `KeyPressed(key: Keycode)` and `KeyReleased(key: Keycode)`

**Comment by kvark** [comment]
I like the Godot/Nitro engine model of describing higher-level input primitives like `Action` or `Slider`, which are bound to keys/mouse/joysticks, so that the game only deals with that higher-level after it's set up.

**Comment by kvark** [comment]
Relevant [PR in Amethyst](https://github.com/amethyst/amethyst/pull/247)

**Comment by kvark** [comment]
An interesting complication here is the split between absolute state and differential state. I.e. we need the current set of keys pressed as well as the list of all keys pressed since the last frame. Similarly, we have the time delta, and we need the absolute time. It's tempting to put those into a single struct, but logically they should be separate.

**Comment by vitvakatu** [comment]
I think it's okay to hold it all in single struct `Events`. It makes it much simpler to use, imo.
Or we can split it to `Events` (all input stuff) and `Time` (absolute time and delta time).

**Comment by kvark** [comment]
@vitvakatu I'm having a bit of difficulty with coming up with a nice design and ergonomics here. In particular, it's tempting to have the `Axis` support both keyboard and mouse axis, but the semantics of these are completely different because one is descreet and another is continuous.
